version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/testerlex/Restaurant-App"